# Generated by Django 3.2.5 on 2021-07-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='gender_img/'),
        ),
    ]
